# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3284c4e7c0b4a1e6b6be3af06b6edc76c46d38eca96900b5af7a7bc3da4f9e700d700092f88cc411d679ffb978b01605a2b0fb860002faca23139d865a9542c9

test:
  secret_key_base: 14e6ef3ccea0cdc211eec8c8d46a1035f96c777dd3f1efee605c5ec2be916dc00ebb77289782e44638ac2bdd1cde5b2523c247e6679990efc5ec760c31dc45b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
